const { MessageEmbed } = require("discord.js");
module.exports = {
  config: {
    name: "createInvite",
    usage: "createInvite",
    aliases: [],
    description: "Create invite for current channel",
    ownerOnly: false,
    enabled: true,
  },
  async run(client, message, args) {
    let channel = message.guild.channels.cache.find(message.channel.id);
    let inviteOption = {
      temporary: false,
      maxAge: 0,
      maxUses: 1,
      unique: false,
      reason: "Generated by wrose",
    };
    let invite = await channel.createInvite(inviteOption);
    message.channel.send({
      embed: {
        color: 3447003,
        fields: [
          {
            name: "Invite generated",
            value: "https://discord.com/invite/" + invite.code,
          },
        ],
        image: {
          url: message.mentions.users
            .first()
            .avatarURL({ format: "png", dynamic: true, size: 1024 }),
        },
        author: {
          name: message.client.user.username,
          icon_url: message.client.user.avatarURL({
            format: "png",
            dynamic: true,
            size: 1024,
          }),
        },
      },
    });
  },
};
